### ISSUE TITLE
Нужен новый релиз

### ISSUE THREAD

**Issue by jungornti** [kmike/django-robokassa#7]
Добрый день, просьба сделать релиз и залить его в pypi, т.к. актуальная версия кода в master не совпадает с последним релизом 1.2.

И ещё, робокасса изменила адрес тестового сервера, его бы тоже поменять в conf.py:

https://auth.robokassa.ru/Merchant/Index.aspx

Спасибо.

**Comment by jungornti** [comment]
Да, и теперь они требуют в тестовом режиме добавлять параметр IsTest=1 к параметрам запроса, иначе считается, что это запрос на реальную оплату.

**Comment by PekopT** [comment]
@jungornti может стоит форкнуть и поправить все у себя? мне тоже нужна рабочая версия

**Comment by kmike** [comment]
Если сделаете PR с необходимыми изменениями, могу залить новый релиз :)

**Comment by PekopT** [comment]
@kmike да там их за год накопилось...
@rganeyev вот например дней 10 назад пилил что-то в своем форке. может подсобит?

**Comment by MrYoda** [comment]
https://github.com/DirectlineDev/django-robokassa-merchant
Некоторое время назад перепилил немного и использовал. Вчера решил довести до релиза на pypi. В коде есть тудушки, PRы принимаются.

**Comment by kmike** [comment]
Спасибо! Сделал релиз 1.3.

**Comment by kmike** [comment]
См. https://github.com/kmike/django-robokassa/issues/9
